### ISSUE TITLE
Minor issues evaluation report

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/Montelukast-Model#5]
@Incei attached are some inor comments on the evaluation report
[montelukast_evaluation_report_AD.pdf](https://github.com/Open-Systems-Pharmacology/Montelukast-Model/files/5062385/montelukast_evaluation_report_AD.pdf)

**Comment by Incei** [comment]
Report has been updated, thanks for Reviewing!

**Comment by Yuri05** [comment]
@Incei are those issues addressed in the last Pull Request?

**Comment by Incei** [comment]
yes! :)
