### ISSUE TITLE
Minor issues in evaluation report created with v10

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/Montelukast-Model#8]
Attached are some comments of the evaluation report for montelukast created with v10
[Montelukast_evaluation_report_AD.pdf](https://github.com/Open-Systems-Pharmacology/Montelukast-Model/files/7337506/Montelukast_evaluation_report_AD.pdf)

@Incei

**Comment by Incei** [comment]
revised and commited for pull-requestion.
the issue with PDF conversion of the table 2.2.1 In vitro / physicochemical data, causing text overlap, i cannot solve @Yuri05   any solution for this?

**Comment by Yuri05** [comment]
fixed with last PR
